// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {main} from '../models';
import {store} from '../models';
import {logging} from '../models';
import {config} from '../models';

export function AddFiles():Promise<service.ImportResult>;

export function ClearLogs():Promise<void>;

export function ClearStaging():Promise<main.ClearStagingResult>;

export function Commit():Promise<main.CommitResult>;

export function ConfirmAddFiles(arg1:Array<string>):Promise<service.ImportResult>;

export function Export(arg1:string,arg2:string):Promise<main.ExportResult>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetArchive():Promise<Array<store.ArchiveEntry>>;

export function GetConfig():Promise<main.ConfigView>;

export function GetGridHeader(arg1:string):Promise<main.GridHeader>;

export function GetLogs(arg1:number):Promise<Array<logging.Entry>>;

export function GetStagingFiles():Promise<main.StagingFilesView>;

export function GetStatus():Promise<main.Status>;

export function GetWeeks(arg1:number):Promise<Array<number>>;

export function GetYears():Promise<Array<number>>;

export function ImportFolder():Promise<service.ImportResult>;

export function QueryData(arg1:main.GridQuery):Promise<store.GridResult>;

export function Quit():Promise<void>;

export function ReportFrontendError(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResetConfig():Promise<main.ConfigView>;

export function RevealExport(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<Array<string>>;
