// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles() {
  return window['go']['main']['App']['AddFiles']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ClearStaging() {
  return window['go']['main']['App']['ClearStaging']();
}

export function Commit() {
  return window['go']['main']['App']['Commit']();
}

export function ConfirmAddFiles(arg1) {
  return window['go']['main']['App']['ConfirmAddFiles'](arg1);
}

export function Export(arg1, arg2) {
  return window['go']['main']['App']['Export'](arg1, arg2);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetArchive() {
  return window['go']['main']['App']['GetArchive']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetGridHeader(arg1) {
  return window['go']['main']['App']['GetGridHeader'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetStagingFiles() {
  return window['go']['main']['App']['GetStagingFiles']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetWeeks(arg1) {
  return window['go']['main']['App']['GetWeeks'](arg1);
}

export function GetYears() {
  return window['go']['main']['App']['GetYears']();
}

export function ImportFolder() {
  return window['go']['main']['App']['ImportFolder']();
}

export function QueryData(arg1) {
  return window['go']['main']['App']['QueryData'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReportFrontendError(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReportFrontendError'](arg1, arg2, arg3);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function RevealExport(arg1) {
  return window['go']['main']['App']['RevealExport'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
